runtime: php
env: flex
runtime_config:
    document_root: .
env_variables:
    APP_LOG: errorlog
    GOOGLE_STORAGE_BUCKET: "staging.premium-odyssey-308704.appspot.com"
    MYSQL_USER: "root"
    MYSQL_PASSWORD: "IH6LzrfE08vpdMpl"
    MYSQL_DSN: "mysql:dbname=GAMdb;unix_socket=/cloudsql/premium-odyssey-308704:us-east4:googleadmanager"
beta_settings:
    cloud_sql_instances: "premium-odyssey-308704:us-east4:googleadmanager"